language: go
go:
- '1.10'
sudo: false
install:
- go get -v github.com/alecthomas/gometalinter
- gometalinter --install
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -d -t -v ./...
  - go test -v ./...
  - ./goclean.sh
notifications:
  email:
    recipients:
        nkbai@163.com
    on_success: change
    on_failure: always
